'use client';
import toast from 'react-hot-toast';
import Link from 'next/link';import {usePathname,useRouter} from 'next/navigation';import {useEffect,useRef,useState} from 'react';import {api,User} from '@/lib/api';
export function Icon({name,size=18}:{name:string;size?:number}){const shapes:Record<string,React.ReactNode>={arrow:<><path d="M5 12h14m-6-6 6 6-6 6"/></>,search:<><circle cx="11" cy="11" r="7"/><path d="m16 16 4 4"/></>,code:<><path d="m8 8-4 4 4 4m8-8 4 4-4 4m-3-11-2 14"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18"/></>,users:<><circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2m2-13a3 3 0 0 1 0 6m1 5a5 5 0 0 1 3 4"/></>,copy:<><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/></>,check:<path d="m4 12 5 5L20 6"/>,plus:<path d="M12 5v14M5 12h14"/>,close:<path d="M5 5l14 14M19 5 5 19"/>,alert:<><path d="M12 3 2 21h20L12 3Z"/><path d="M12 9v5m0 3h.01"/></>,download:<><path d="M12 3v12m-4-4 4 4 4-4M4 17v4h16v-4"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{shapes[name]}</svg>}
export function Brand(){return <Link href="/" className="brand"><span className="brand-mark">W</span><span>workshop<span className="accent">/</span>space</span></Link>}
export function Header(){const [user,setUser]=useState<User|null>(null);const [ready,setReady]=useState(false);const path=usePathname();const router=useRouter();useEffect(()=>{api<{user:User}>('/auth/me').then(d=>setUser(d.user)).catch(()=>setUser(null)).finally(()=>setReady(true));},[path]);async function signout(){const previous=user;setUser(null);window.dispatchEvent(new CustomEvent('workshop-auth-changed',{detail:null}));try{await api('/auth/logout',{method:'POST'});toast.success('Signed out');router.replace('/');router.refresh()}catch(error){setUser(previous);window.dispatchEvent(new CustomEvent('workshop-auth-changed',{detail:previous}));toast.error((error as Error).message)}}return <header className="header"><div className="wrap header-inner"><Brand/><nav><a href="#explore" className="header-section-link">Explore</a>{ready&&(user?<><a href="#my-rooms" className="header-section-link">My rooms</a><span className="header-person">{user.name}</span><button className="nav-button" onClick={signout}>Sign out</button></>:<><Link href="/auth">Log in</Link><Link className="button primary small" href="/auth?mode=register">Sign up <Icon name="arrow" size={15}/></Link></>)}</nav></div></header>}
export function Notice({children}:{children:React.ReactNode}){return <div className="notice" role="alert">{children}</div>}
export function Loading(){return <div className="loading"><span className="spinner"/> Loading...</div>}
export function ContentSkeleton(){return <div className="content-skeleton" aria-label="Loading content"><span/><span/><span/><span/></div>}
export function Empty({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="empty"><span className="empty-symbol"><Icon name="code" size={26}/></span><h3>{title}</h3><p>{description}</p>{action}</div>}
export function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')close()};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[close]);return <div className="modal-shade" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-title"><h2>{title}</h2><button onClick={close} aria-label="Close"><Icon name="close"/></button></div>{children}</div></div>}
export function useAuth(required=true){const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);const version=useRef(0);const router=useRouter();useEffect(()=>{let active=true;const requestVersion=version.current;api<{user:User}>('/auth/me').then(d=>{if(active&&version.current===requestVersion)setUser(d.user)}).catch(()=>{if(active&&version.current===requestVersion){setUser(null);if(required)router.replace('/auth')}}).finally(()=>{if(active&&version.current===requestVersion)setLoading(false)});const changed=(event:Event)=>{version.current++;setUser((event as CustomEvent<User|null>).detail);setLoading(false)};window.addEventListener('workshop-auth-changed',changed);return()=>{active=false;window.removeEventListener('workshop-auth-changed',changed)}},[router,required]);return {user,loading}}
